### ISSUE TITLE
Any way to cache the apt stuff?

### ISSUE THREAD

**Issue by cjnqt** [jontewks/puppeteer-heroku-buildpack#1]
Is there any way to cache the apt fetching stuff, to speed up deployment?

**Comment by jontewks** [comment]
@cjnqt not that I'm aware of. I looked into it briefly and wasn't able to find anything regarding caching these sorts of things. Also the buildpack I created was based largely off of the [heroku created headless chrome buildpack](https://github.com/heroku/heroku-buildpack-google-chrome) and does these apt-installs in the same exact way. So it seems there is no way to currently do this.
