### ISSUE TITLE
Don't work with an other buildpacks (pdftk)

### ISSUE THREAD

**Issue by GautierT** [jontewks/puppeteer-heroku-buildpack#10]
Hi,
Thanks for this buildpack !
I'm now trying to make it work with https://github.com/fxtentacle/heroku-pdftk-buildpack
When i add https://github.com/fxtentacle/heroku-pdftk-buildpack to my buildpack list Chrome doesn't want to start : 
```
Error: kill ESRCH
at Object._errnoException (util.js:1024:11)
at process.kill (internal/process.js:183:18)
at forceKillChrome (/app/node_modules/puppeteer/lib/Launcher.js:164:19)
at killChrome (/app/node_modules/puppeteer/lib/Launcher.js:149:9)
at Function.launch (/app/node_modules/puppeteer/lib/Launcher.js:139:7)
at <anonymous>
```

Must be a problem of path maybe ? I don't really understant everything on the compile file of the buildpack so any help will be useful !

Thanks.

**Comment by jontewks** [comment]
Woah! Sorry I didn't see this issue and must have missed the email somehow, 25 days ago is a long wait!

Is this still happening to you? If so can you verify you are using the flags as mentioned in the readme  of my buildpack for no sandbox? Thanks!

**Comment by GautierT** [comment]
No problem ! It was a path problem on https://github.com/fxtentacle/heroku-pdftk-buildpack !
It's fixed now. Thanks.

**Comment by johnrhampton** [comment]
Thanks for the info @GautierT, I was running into this same issue.  Using the fork from https://github.com/jayroh/heroku-pdftk-buildpack worked great.
