### ISSUE TITLE
"Error: Failed to launch chrome!"

### ISSUE THREAD

**Issue by Joblyn** [jontewks/puppeteer-heroku-buildpack#106]
Trying to use puppeteer in my application. 
When deploying to heroku, the build keeps throwing the following error;
```bash
remote: Error: Error: Failed to launch chrome!
remote: /tmp/build_012ea572/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
```

Tried installing the `jontewks/puppeteer` heroku buildpack; both the stable version and source code as recommended, but the error persists.

Here's my puppeteer launch function:
```JS
const chromiumArgs = [
  '--no-sandbox',
  '--no-zygote',
  '--disable-gpu',
  '--ignore-certificate-errors',
  '--allow-running-insecure-content',
  '--disable-web-security',
  `--user-data-dir=${CHROMIUM_DATA_DIR || '/tmp/chromium'}`,
]
   puppeteer.launch({
          ignoreHTTPSErrors: true,
          acceptInsecureCerts: true,
          args: chromiumArgs,
          executablePath: CHROMIUM_BIN,
        })
```
Here's an attached screenchot of the error log.
<img width="1169" alt="Screenshot 2022-07-10 at 22 33 29" src="https://user-images.githubusercontent.com/62160764/178162821-b3a28baf-c4d3-4644-9d44-99bc82b74d56.png">

Any help in resolving this would be appreciated.

**Comment by jontewks** [comment]
Have you tried it without `executablePath` so it would use the bundled version of chromium? If you are using a different version of chromium you might have different package requirements and need to work from there and add them. You might also try clearing the build cache if the chromium version isn't the root cause. 

https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

**Comment by Joblyn** [comment]
> Have you tried it without `executablePath` so it would use the bundled version of chromium? If you are using a different version of chromium you might have different package requirements and need to work from there and add them. You might also try clearing the build cache if the chromium version isn't the root cause.
> 
> https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

Tried this @jontewks but the error still persists.
I use macOS, if that's a factor.

**Comment by jontewks** [comment]
Are you able to share the code so I can try to run it? Might also try making sure puppeteer is up to date, you are on the newest heroku stack, or deploying it as is to a new project to be sure something isn't cached and sticking around, that has helped in the past with a slug size issue.

**Comment by Joblyn** [comment]
@jontewks Alright.
Here's the repo
https://github.com/Joblyn/wappalyzer/tree/Joblyn
Use the `Joblyn` branch.
Use command instructions in `README.md`

**Comment by jontewks** [comment]
Any change if you call it with less arguments? I've got a minimum testing repo for the buildpack running just using the no-sandbox flag only.

Perhaps a good test would be to do this minimum code version and see if it works or not. If it works, there is something in your code requiring additional packages, so you can just extend the buildpack, or if it doesn't work, we know something is up with your cache or app.

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox'] })
  const page = await browser.newPage()
  await page.goto('https://www.buildingconnected.com')

  console.log('WORKING')

  await browser.close()
  process.exit(0)
})()
```
