### ISSUE TITLE
Always timeout error only in production

### ISSUE THREAD

**Issue by farizrachmansyah** [jontewks/puppeteer-heroku-buildpack#107]
Hi
I had no issues at all running my Puppeteer project in my development environment. But why do I always get timeout error when running it in heroku production environment? I got so overwhelmed fixing this issue. It would be much appreciated if someone could help me to fix this issue. Thank you
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/44774650/181371588-97b3ce57-7e0d-4db8-a4b3-e83887d1acb1.png">

My puppeteer codes
https://github.com/farizrachmansyah/scrapesi/blob/main/jobscraper.js

**Comment by jontewks** [comment]
So sounds like that selector isn't show up when doing this on heroku for some reason. This buildpack is only for getting puppeteer running on heroku, but doesn't have anything to do with how it runs after that. 

I'd suggest taking a screenshot of what is seen by puppeteer at this point to get an idea of why that selector you expect to be there isn't there when using puppeteer through heroku.
