### ISSUE TITLE
Please support heroku-22 stack

### ISSUE THREAD

**Issue by ngwaemail** [jontewks/puppeteer-heroku-buildpack#108]
For some reason I don't understand, this buildpack doesn't work on apps using the modern heroku-22 stack. We get the error "libnss3.so not found", during runtime.

**Comment by jontewks** [comment]
Please check that you are using the latest version of the buildpack or potentially need to clear your cache, this supports Heroku-22

![2022-08-09_10-43-45](https://user-images.githubusercontent.com/3970573/183698341-66a47dff-e811-45fb-941a-e03d33ab2af3.png)
