### ISSUE TITLE
Add #18.0.0 and #20.0.0 tags for users on older stacks

### ISSUE THREAD

**Issue by robotfelix** [jontewks/puppeteer-heroku-buildpack#113]
Thanks for your work on this convenient buildpack and the recent updates for compatibility with the Heroku-22 stack!

My understanding is that the latest `main` of this branch no longer installs all the necessary dependencies for the Heroku-18 and Heroku-20 stack, as I'm now running into some errors due to a missing libcairo-gobject.so.2 (on the Heroku-18 stack).

The implication of the new suggestion to point to a specific tag is that any users of older stacks need to change their buildpack from just `jontewks/puppeteer` to the last version _before_ the `#22.0.0` tag.

The last tag before `#22.0.0` seems to be `#1.1.7`, but this was released all the way back on 18th April 2020. The Heroku-22 stack was [only released on 15th June 2022](https://devcenter.heroku.com/changelog-items/2429), so using the `#1.1.7` tag means missing out on over 2 years of updates you made for use with the Heroku-18 and Heroku-20 stacks before Heroku-22 came along. In fact, the version with the `#1.1.7` tag has a stack check that fails for the Heroku-20 stack, so in practice I think there isn't **_any_** suitable tag for that stack!

Is it possible you could add some a tag to the last "pre-Heroku-22" version of this buildpack? My suggestion would be to add both `#18.0.0` and `#20.0.0` to fit with your new naming convention :)

In the meantime, I've gotten things working by pointing directly to the commit before the Heroku-22 updates started, eg: using
```
https://github.com/jontewks/puppeteer-heroku-buildpack#ffaa6f7da5a3f486f5ac2d60cd87ee0e5ae9b429
```
as the buildpack URL.

**Comment by jontewks** [comment]
Hey @robotfelix thanks for the info.

I didn't make those previous tags as from what I could tell it appeared as if this version should work for the previous stacks. If you take a look at https://devcenter.heroku.com/articles/stack-packages you'll see what packages are already available on the various heroku stacks. You'll see the one you wrote in about is available at build time but apparently not at run time. I'll make an 18 version with that included. Would you update this if there are any new requirements that I missed? I'm not able to make new apps on older stacks so its hard to check on these.

**Comment by jontewks** [comment]
Here's the tag. Let me know how that goes: https://github.com/jontewks/puppeteer-heroku-buildpack/releases/tag/v18.0.0

**Comment by jontewks** [comment]
Just let me know if it doesn't, I may have missed one package moving from run time to build time only on the heroku stack or something.
