### ISSUE TITLE
Error: Run `npm install` to download the correct Chromium revision (1056772)

### ISSUE THREAD

**Issue by RexVaga** [jontewks/puppeteer-heroku-buildpack#116]
I am getting the error "Run `npm install` to download the correct Chromium revision (1056772)" in my Heroku logs when executing the below code:
`const browser = await puppeteer.launch({headless: true ,
        args : [
          '--no-sandbox',
          '--disable-setuid-sandbox',
        ]
      });`

I have tried using https://github.com/jontewks/puppeteer-heroku-buildpack, https://github.com/jontewks/puppeteer-heroku-buildpack#22.0.0, and https://github.com/jontewks/puppeteer-heroku-buildpack#22.0.0-no-xdg-utils with no luck.

I also have my caching turned off in Heroku:
![image](https://user-images.githubusercontent.com/20868801/199289790-f5caac8e-aa6b-4085-846e-ef1d002e31e5.png)

In addition to all of this, I have even tried executing `node node_modules/puppeteer/install.js` via `heroku run bash`.

Any help is much appreciated!

**Comment by jontewks** [comment]
Please reset Heroku cache. Instructions are here: https://github.com/jontewks/puppeteer-heroku-buildpack#caching

This is from a change Puppeteer made in v 19 and isn't related to the build pack.

**Comment by RexVaga** [comment]
I somehow missed https://github.com/jontewks/puppeteer-heroku-buildpack/issues/115, where my question was already answered. Specifying the Puppeteer version in my package.json (`"puppeteer": "18.1.0",` in my case) resolved the issue.
