### ISSUE TITLE
puppeteer.lauch doesn't run after heroku deploy

### ISSUE THREAD

**Issue by cosminfiliphusi** [jontewks/puppeteer-heroku-buildpack#118]
Code ***

static async saveHtmlToPdf(req:Request, res:Response){
    try{
      const {id} = req.params
      console.log("aici :", id)
      const browser = await puppeteer.launch({ 
        headless:true,
        defaultViewport: null,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
        ] 
      });
      console.log("browser :", browser)
      const page = await browser.newPage();
      console.log("page asdfsa :", page)
      await page.goto(`https://marity.herokuapp.com/api/proform/template1/${id}`, {waitUntil: 'networkidle0'});
      const pdf = await page.pdf({format: 'A4', printBackground:true });
      console.log(pdf)
      await browser.close();
     res.set({ 'Content-Type': 'application/pdf', 'Content-Length': pdf.length })
      res.send(pdf)
    }
    catch(e){
      res.send(e)
    }
  }
--------------------------------------------------
Heroku buildpacks ***

% heroku buildpacks --app=marity
=== marity Buildpack URLs
1. jontewks/puppeteer
2. heroku/nodejs
--------------------------------------------------
Heroku log ***

2022-11-08T09:23:34.693779+00:00 heroku[router]: at=info method=GET path="/api/proform/saveHtmlToPdf/6345983facdde8d1bb7d6f55" host=marity.herokuapp.com request_id=9a8d3eef-6182-4e83-ab89-478571432af7 fwd="86.124.130.239" dyno=web.1 connect=0ms service=13ms status=304 bytes=181 protocol=https
2022-11-08T09:23:34.689822+00:00 app[web.1]: aici : 6345983facdde8d1bb7d6f55
2022-11-08T09:23:34.693202+00:00 app[web.1]: ::ffff:10.1.3.188 - - [08/Nov/2022:09:23:34 +0000] "GET /api/proform/saveHtmlToPdf/6345983facdde8d1bb7d6f55 HTTP/1.1" 304 -
----------------------------------------------
In localhost everything its Ok. 
When i deploy on heroku i've recive " {} ", and in console i don't get the console.log from browser.
In heroku log i don't have errors.
Puppeteer.launch() do nothing in heroku

**Comment by jontewks** [comment]
Hello.

This buildpack does nothing more than allows Puppeteer to run on Heroku. Since this issue you are seeing is after Puppeteer has started up it lies outside of the buildpack. I do notice from your logs though you're getting a 304 back which could be part of your issue. You might also have some luck taking a screenshot with Puppeteer to see what Heroku is seeing at the time it fails for you.
