### ISSUE TITLE
TypeError: page.waitForTimeout is not a function

### ISSUE THREAD

**Issue by welearntrading** [jontewks/puppeteer-heroku-buildpack#121]
Hi guys

I'm getting this error when calling the page.waitTimeout function
TypeError: page.waitForTimeout is not a function

`await page.waitForTimeout(4000)`

However, the page.waitFor function works

I'm using your buildpacks made for Heroku stacks 22
https://github.com/jontewks/puppeteer-heroku-buildpack#22.0.0

What am I missing to get the waitForTimeout function to work?

Thank you

**Comment by jontewks** [comment]
Hey @welearntrading.

This buildpack only gets puppeteer running on heroku and doesn't change how it works after it's running. If any issues like this pop up in the future I'd suggest going to the puppeteer repo to ask, or checking the docs. I did a quick search for the docs for that function and saw this:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/3970573/206216426-4e9994ec-35de-44d7-a477-493e4cda2857.png">

https://pptr.dev/api/puppeteer.page.waitfortimeout

Looks like that function was removed at some point in favor of just doing it with a promise.
