### ISSUE TITLE
 Error: Could not find Chromium (rev. 1095492)

### ISSUE THREAD

**Issue by IonicaBizau** [jontewks/puppeteer-heroku-buildpack#123]
We installed `Puppeteer 19` and we are getting the following error on Heroku Stack 22. It may be that some dependencies are missing...

```
Error: Could not find Chromium (rev. 1095492). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /app/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:127:27)
    at ChromeLauncher.executablePath (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:206:25)
    at ChromeLauncher.launch (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:93:37)
    at async module.exports (/app/pdf.js:11:21)
    at async Promise.all (index 0)
```

**Comment by jmcgill** [comment]
@IonicaBizau There's a few closed issues related to this. It's due to a change in how Pupeteer works - not anything related to this buildpack.

I finally got things working by downgrading to Pupeteer 18.1.0 (anything higher didn't work) and clearing the build cache, following the instructions in the README of this repository.

**Comment by jontewks** [comment]
Clearing the build cache should work, but I've seen before where it seems like Heroku doesn't clear the full cache, or there is some other cache that causes things to stick around. I've fixed that by just creating a new Heroku app with the same code. Perhaps you can try clearing the cache, and if that doesn't work, either downgrade Puppeteer versions or create a new Heroku app if you'd like to use the latest.
