### ISSUE TITLE
Heroku : error while loading shared libraries: libX11-xcb.so.1, failed to launch chrome

### ISSUE THREAD

**Issue by Nicolas-vrcc** [jontewks/puppeteer-heroku-buildpack#13]
Hello,

I'm trying to launch a puppeteer script using heroku and I did everything properly, I use these buildbacks:
```
1. https://github.com/jontewks/puppeteer-heroku-buildpack 
3. heroku/nodejs
```

But I'm still getting this error :

```
Error: Failed to launch chrome!
/app/node_modules/puppeteer/.local-chromium/linux-526987/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
```

**Comment by jontewks** [comment]
Hey @Nicolas-vrcc. Have you tried changing the buildpack order? A few people have mentioned that as a fix to some random issues, not sure what the cause is but worth a shot.

**Comment by jontewks** [comment]
Haven't heard back in over a week. Feel free to reopen if you are still running into issues and the above didn't resolve it. Would like to hear either way how it was resolved for future people running into the same thing.

**Comment by tao** [comment]
I had this issue too, it might be related. 

Remember to deploy the code again in order to install the build pack correctly... restarting the dyno won't do it. You'll know it's installed correctly when you get the "Google Chrome" next to framework.

![screen shot 2018-04-04 at 00 06 38](https://user-images.githubusercontent.com/1446331/38278595-fa956cf4-379c-11e8-8651-321f619f14ae.png)

**Comment by heshamelmasry77** [comment]
@jontewks  Hey i am actually running in to the same error and can't find a solution

**Comment by jontewks** [comment]
@heshamelmasry77 after changing the order did you deploy some code, as @tao mentioned, simply changing the order doesn't do anything, you need to run a full deploy so that heroku will build everything again, simply restarting dynos won't do it.

**Comment by heshamelmasry77** [comment]
@jontewks Hey so i found the solution to this problem.
If you the people were facing problem like what i faced when i tried to deploy my app and i have react-snap so the solution is : first we add these build packs in the following order
<img width="823" alt="screen shot 2018-05-11 at 11 03 14" src="https://user-images.githubusercontent.com/15607302/39916504-f03599f6-550a-11e8-9615-c9e98f9c1182.png">
and then we remove from the package.json this 
```  
   "postbuild": "react-snap"
```
and then deploy the app so it build the build packs
after this google chrome will appear next to the node js in the framework in heroku
then to add react snap we add to package.json 

```
"reactSnap": {
    "cacheAjaxRequests": true,
    "inlineCss": true,
    "http2PushManifest": true,
    "puppeteerArgs": ["--no-sandbox", "--disable-setuid-sandbox"]
  }
```
and also to the scripts in package.json this : 
```
    "postbuild": "react-snap"
```
and here is an example if my package.json to help :)
```
{
  "name": "react-ui",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/react": "^16.0.25",
    "auth0-js": "^9.3.3",
    "axios": "^0.17.1",
    "bootstrap": "^3.3.7",
    "flow-bin": "^0.57.3",
    "history": "^4.7.2",
    "install": "^0.10.1",
    "lint-staged": "^4.3.0",
    "node-sass-chokidar": "0.0.3",
    "npm": "^5.5.1",
    "npm-run-all": "^4.1.2",
    "prettier": "^1.8.2",
    "prop-types": "^15.6.1",
    "react": "^16.2.0",
    "react-bootstrap": "^0.31.5",
    "react-bootstrap-table": "^4.3.0",
    "react-dom": "^16.1.1",
    "react-dropzone": "^4.2.3",
    "react-helmet": "^5.2.0",
    "react-icons": "^2.2.7",
    "react-loadable": "^5.3.1",
    "react-notify-toast": "^0.4.0",
    "react-recaptcha": "^2.3.7",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.17",
    "react-skylight": "^0.5.0",
    "react-snap": "^1.12.2",
    "react-tap-event-plugin": "^3.0.2",
    "redux": "^3.7.2",
    "redux-form": "^7.2.0",
    "styled-components": "^2.2.3"
  },
  "lint-staged": {
    "src/**/*.{js,jsx,json,css}": [
      "prettier --single-quote --write",
      "git add"
    ]
  },

  "scripts": {
    "build-css": "node-sass-chokidar src/ -o src/",
    "watch-css": "yarn run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "serve": "yarn npm-run-all -p watch-css start-js",
    "heroku-postbuild": "yarn --production=true && yarn run build",
    "build-js": "react-scripts build",
    "build": "npm-run-all build-css build-js",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "flow": "flow",
    "postbuild": "react-snap"
  },
  "reactSnap": {
    "cacheAjaxRequests": true,
    "inlineCss": true,
    "http2PushManifest": true,
    "puppeteerArgs": ["--no-sandbox", "--disable-setuid-sandbox"]
  },
  "author": "Hesham El Masry <heshamelmasry@outlook.com>",
  "devDependencies": {
    "react-scripts": "1.0.17"
  },
  "proxy": "https://www.heshamelmasry.website",
  "homepage": "https://www.heshamelmasry.website"
}

```

**Comment by agoldis** [comment]
For others looking for a solution, setting the proper order solved the problem for me:
```
"buildpacks": [
    {
      "url": "https://github.com/jontewks/puppeteer-heroku-buildpack.git"
    },
    {
      "url": "heroku/nodejs"
    }
```

**Comment by Ancinek** [comment]
I've had the same problem and almost solved it by using this setup, however – my slug size exceeds `500mb` with all that puppeteer/chrome buildpacks. Is there a way I can minimize the slug size?

**Comment by jontewks** [comment]
@Ancinek have you come across this list yet? https://thoughtbot.com/blog/how-to-reduce-a-large-heroku-compiled-slug-size. Clearing the cache has helped me in the past

**Comment by Ancinek** [comment]
@jontewks I will definitely have a look at this one!
