### ISSUE TITLE
mv: cannot stat '/app/.cache/puppeteer': No such file or directory

### ISSUE THREAD

**Issue by opeyemidy** [jontewks/puppeteer-heroku-buildpack#130]
```
 > mkdir ./.cache && mv /app/.cache/puppeteer ./.cache
       
mv: cannot stat '/app/.cache/puppeteer': No such file or directory
-----> Build failed
```

**Comment by CryptoTuck** [comment]
running into the same issues. Have you seen this issue yet? @jontewks

**Comment by opeyemidy** [comment]
I had to downgrade puppeteer

**Comment by ElitKondor** [comment]
@opeyemidy Downgrade to which version?

**Comment by opeyemidy** [comment]
`"puppeteer": "^16.2.0",`

**Comment by ElitKondor** [comment]
@opeyemidy It really helped. Thanks!

**Comment by hitwill** [comment]
This fixed it for me:
Make sure the puppeteer buildpack is placed before the node js:

1. Puppeteer
2. NodeJS

For your  package.json, add this line as the last thing to do after building everything else
```js
 "scripts": {
    "build": "node node_modules/puppeteer/install.js && mkdir -p ./.cache && mv /app/.cache/puppeteer ./.cache",
}
```

before deploying:
`heroku builds:cache:purge -a YOUR_APP`

**Comment by opeyemidy** [comment]
@hitwill does it work with the latest version of puppeteer?

**Comment by geniuscd** [comment]
having the same issue here :/

**Comment by ElitKondor** [comment]
I downgraded puppeteer to "puppeteer": "^16.2.0" and did not use presented script command. 
The rest is the same as hitwill said.
As heroku puppeteer buildpack i'm using a link to this repo ("https://github.com/jontewks/puppeteer-heroku-buildpack").
Don't remember to reorder buildpacks (Puppeteer -> Node) and redeploy something to make these changes work

**Comment by hitwill** [comment]
> @hitwill does it work with the latest version of puppeteer?

@opeyemidy yes. I am using: "puppeteer": "^21.2.0"

**Comment by opeyemidy** [comment]
@hitwill 

i'm getting thid 

`Error: Cannot find module '/tmp/build_25b7743d/node_modules/puppeteer/install.js'`

**Comment by hitwill** [comment]
> install

@opeyemidy try `node node_modules/puppeteer/install.mjs`

(mjs instead of js)

**Comment by opeyemidy** [comment]
worked thanks @hitwill

**Comment by nazreen** [comment]
@hitwill  how were you able to find the solution? thank you!

**Comment by nazreen** [comment]
ok I am facing a weird thing where, 

if I purge, then trigger a deploy, it would work

but then if there is another deploy triggered, it would complain about the same error that is the title of this issue

**Comment by hitwill** [comment]
> ok I am facing a weird thing where,
> 
> if I purge, then trigger a deploy, it would work
> 
> but then if there is another deploy triggered, it would complain about the same error that is the title of this issue

Follow the conversation from here

> @hitwill how were you able to find the solution? thank you!

Follow the conversation from here: https://github.com/jontewks/puppeteer-heroku-buildpack/issues/130#issuecomment-1720774565

**Comment by Agill-Sheron** [comment]
Thank you @hitwill 🙏

**Comment by zachsj** [comment]
@hitwill You seem to be the guru around here.  I made sure the build pack was before NodeJS, added the script to .json file (used mjs) and then purged.  Does this not all apply if using Next.js?  I keep getting this in the logs "[Error: ENOENT: no such file or directory, open '/app/.next/BUILD_ID']"  and this.. State changed from starting to crashed at=error code=H10 desc="App crashed".  Is this just other non relevant issues maybe?

**Comment by jdebeer** [comment]
@hitwill I am also not getting this to work now... in package.json, I have
```
  "scripts": {
    "build": "node node_modules/puppeteer/install.mjs && mkdir -p ./.cache && mv /app/.cache/puppeteer ./.cache",
    ...
   }
```

after purging and deploying with that config, the build then fails;
```
remote:        Chrome (122.0.6261.69) downloaded to /tmp/build_748b4aab/.cache/puppeteer/chrome/linux-122.0.6261.69
remote:        chrome-headless-shell (122.0.6261.69) downloaded to /tmp/build_748b4aab/.cache/puppeteer/chrome-headless-shell/linux-122.0.6261.69
remote: mv: cannot stat '/app/.cache/puppeteer': No such file or directory
```

**Comment by zachsj** [comment]
I got it to work by following creating a .cjs file etc from this post https://stackoverflow.com/questions/52225461/puppeteer-unable-to-run-on-heroku

Having some other cloudinary api_key issues now though.

**Comment by jontewks** [comment]
Sorry for slow response here, but looked like it was working in a newer version of puppeteer. I'm also going to update this buildpack for the latest version of heroku, so will be sure latest heroku and latest puppeteer have all the kinks worked out.

**Comment by andpi314** [comment]
> > install
> 
> @opeyemidy try `node node_modules/puppeteer/install.mjs`
> 
> (mjs instead of js)

Worked for me too
