### ISSUE TITLE
Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

### ISSUE THREAD

**Issue by sspread** [jontewks/puppeteer-heroku-buildpack#131]
Running puppeteer 21.3.5 - `headless: 'new'`. Logs error from browser (`dumpio: true`) flag. Mostly works as expected otherwise, but I suspect causes issues with timeout `ProtocolError: Target.createTarget timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.` See discussion https://github.com/puppeteer/puppeteer/pull/11029

**Comment by jontewks** [comment]
Hey @sspread sorry I missed this for so long. I hope you got it all working in my long absence, but this buildpack only installs things on heroku to allow puppeteer to work, and shouldn't be changing how it works after starting.
