### ISSUE TITLE
Mention that the heroku-postbuild script will prevent the build script from running

### ISSUE THREAD

**Issue by tw-pocket** [jontewks/puppeteer-heroku-buildpack#135]
https://devcenter.heroku.com/articles/nodejs-support#:~:text=If%20a%20heroku%2Dpostbuild%20script%20is%20specified%2C%20the%20build%20script%20does%20not%20run.

**Comment by raldred** [comment]
Forgive my ignorance, Is it not possible to have this buildpack create the cache directory, rather than relying on `heroku-postbuild`?

**Comment by gabrielmtns** [comment]
For now to fix that i am forcing build on heroku-postbuild.
     
`"heroku-postbuild": "npm run build && mkdir  ./.cache && mv /app/.cache/puppeteer ./.cache"
`

 But that doesn't seem like an ideal solution to me.

**Comment by camdagr8** [comment]
I get an error when using the heroku-postbuild script: 

```
mv: cannot stat '/app/.cache/puppeteer': No such file or directory
```

**Comment by jontewks** [comment]
Sorry for slow response here. Just added to readme. Feel free to open PRs for these and I'd be happy to merge them.

Heroku's docs linked above specifically show adding the build command to the postbuild command as @gmtns mentioned so looks like that might be their solution for it currently.

I'm going to update for the latest heroku version, so maybe some of this will be cleaned up by using newer versions.
