### ISSUE TITLE
Add support for Heroku-24

### ISSUE THREAD

**Issue by edmorley** [jontewks/puppeteer-heroku-buildpack#136]
Heroku-24 was released yesterday:
https://devcenter.heroku.com/changelog-items/2898

Using this buildpack on Heroku-24 currently results in this error:

```
-----> Puppeteer app detected
-----> Detected Stack changes, flushing cache
-----> Updating apt caches
       Get:1 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]
       Get:2 http://archive.ubuntu.com/ubuntu noble InRelease [256 kB]
       Get:3 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
       Get:4 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Packages [65.1 kB]
       Get:5 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
       Get:6 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages [206 kB]
       Get:7 http://archive.ubuntu.com/ubuntu noble/main amd64 Packages [1,808 kB]
       Get:8 http://archive.ubuntu.com/ubuntu noble/universe amd64 Packages [19.3 MB]
       Get:9 https://apt.postgresql.org/pub/repos/apt noble-pgdg InRelease [123 kB]
       Get:10 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [97.3 kB]
       Get:11 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [230 kB]
       Get:12 http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Packages [7,519 B]
       Get:13 https://apt.postgresql.org/pub/repos/apt noble-pgdg/main amd64 Packages [465 kB]
rm: cannot remove '/var/cache/apt/archives/partial/*.deb': Permission denied
       Fetched 23.0 MB in 2s (12.3 MB/s)
       Reading package lists...
-----> Fetching .debs for gconf-service
       Reading package lists...
       Building dependency tree...
E: Unable to locate package gconf-service
```

**Comment by waqas-ahmad762** [comment]
I am also facing the same issue. Other build pack or any solution you found @edmorley ?

**Comment by rdingman** [comment]
I'm also running into this issue. Any help would be appreciated.

**Comment by jontewks** [comment]
Thanks a lot @edmorley!

To the other folks: I’m on vacation at the moment but if you need this fixed more quickly feel free to open a PR that resolves it. Otherwise I’ll take a look as soon as I can but won’t be home till after the 4th.

**Comment by waqas-ahmad762** [comment]
@jontewks thanks for the reply. Have you been able to add support for Heroku-24?

**Comment by edmorley** [comment]
> E: Unable to locate package gconf-service

If it helps, the Heroku Chrome for Testing buildpack no longer installs that package, since it turned out not to be needed for Chrome any more. Whether that's the case or not when using Puppeteer is another matter.

eg see the package list that buildpack installs, here:
https://github.com/heroku/heroku-buildpack-chrome-for-testing/blob/0d6dabcd8d81111c9f1383a2eeb18337cd8d1a25/bin/install-chrome-dependencies#L19-L52

It would likely also be worthwhile to add some tests to this buildpack to check dynamically linked libs can be found at runtime, which would give more confidence in removing unnecessary packages from the list that this buildpack installs during the build. See here for an example of such tests:
https://github.com/heroku/heroku-buildpack-chrome-for-testing/blob/main/bin/test.sh
https://github.com/heroku/heroku-buildpack-chrome-for-testing/blob/main/Dockerfile
https://github.com/heroku/heroku-buildpack-chrome-for-testing/blob/main/.github/workflows/build-and-test.yml

**Comment by jontewks** [comment]
Thanks very much @edmorley, finally back from vacation and other issues that took time. 

Does heroku have any level of subscription for free for buildpack maintenance purposes? My only use case is to be sure the buildpack is running.

**Comment by raldred** [comment]
@jontewks I dont think so not anymore. We'd be happy to provide a test app if that helps?

**Comment by The1987** [comment]
Is there any hot fix that can be made to get this to work like adding gconf-service to .debs ?

**Comment by NEjim2001** [comment]
Currently have the same issue

**Comment by jontewks** [comment]
Hey would someone with heroku access please try out this url as the buildpack and report what happens? This is pointing right to the new branch with updates per puppeteer and heroku for what packages are required and available.

https://github.com/jontewks/puppeteer-heroku-buildpack.git#heroku-24

**Comment by The1987** [comment]
> https://github.com/jontewks/puppeteer-heroku-buildpack.git#heroku-24

Here is what I got:

```
-----> Building on the Heroku-24 stack
-----> Using buildpacks:
       1. https://github.com/jontewks/puppeteer-heroku-buildpack.git#heroku-24
       2. heroku/nodejs
-----> Puppeteer app detected
-----> Reusing cache
-----> Updating apt caches
       Get:1 http://archive.ubuntu.com/ubuntu noble InRelease [256 kB]
       Get:2 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
       Get:3 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
       Get:4 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]
       Get:5 http://archive.ubuntu.com/ubuntu noble/main amd64 Packages [1,808 kB]
       Get:6 http://archive.ubuntu.com/ubuntu noble/universe amd64 Packages [19.3 MB]
       Get:7 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [424 kB]
       Get:8 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [400 kB]
       Get:9 http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Packages [11.5 kB]
       Get:10 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Packages [329 kB]
       Get:11 https://apt.postgresql.org/pub/repos/apt noble-pgdg InRelease [129 kB]
       Get:12 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages [330 kB]
       Get:13 https://apt.postgresql.org/pub/repos/apt noble-pgdg/main amd64 Packages [468 kB]
rm: cannot remove '/var/cache/apt/archives/partial/*.deb': Permission denied
       Fetched 23.9 MB in 1s (19.0 MB/s)
       Reading package lists...
-----> Fetching .debs for fonts-liberation
       Reading package lists...
       Building dependency tree...
       The following additional packages will be installed:
         fonts-liberation-sans-narrow
       The following NEW packages will be installed:
         fonts-liberation fonts-liberation-sans-narrow
       0 upgraded, 2 newly installed, 0 to remove and 21 not upgraded.
       Need to get 1,800 kB of archives.
       After this operation, 4,894 kB of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu noble/main amd64 fonts-liberation all 1:2.1.5-3 [1,603 kB]
       Get:2 http://archive.ubuntu.com/ubuntu noble/main amd64 fonts-liberation-sans-narrow all 1:1.07.6-4 [197 kB]
       Fetched 1,800 kB in 0s (10.7 MB/s)
       Download complete and in download only mode
-----> Fetching .debs for libasound2
       Reading package lists...
       Building dependency tree...
       Package libasound2 is a virtual package provided by:
         liboss4-salsa-asound2 4.2-build2020-1ubuntu3
         libasound2t64 1.2.11-1build2 (= 1.2.11-1build2)
       
E: Package 'libasound2' has no installation candidate
 !     Push rejected, failed to compile Puppeteer app.
 !     Push failed
 ```

**Comment by jontewks** [comment]
Thanks for running that. That package has been in the list for a while, and is still shown as required for puppeteer. I see some issues with it on ubuntu 24 though, will try to get to the bottom of it today.

**Comment by jontewks** [comment]
Ah yes I see the change I was looking to do to libasound2t64 in @edmorley's post of the new requirements as well. Will update now.

**Comment by jontewks** [comment]
Alright updated the branch to install the version of libasound2 that will work on ubuntu 24.

**Comment by The1987** [comment]
@jontewks the build was successful.

**Comment by jontewks** [comment]
Thanks @The1987 just merged this to main. Will update heroku buildpacks list too to be sure it installs the new version
