### ISSUE TITLE
Heroku-16 Failed to launch chrome! error while loading shared libraries: libpng16.so.16

### ISSUE THREAD

**Issue by solarsilk** [jontewks/puppeteer-heroku-buildpack#14]
Thank you for this awesome buildpack!

All was working great on Heroku until today. For some reason Chrome can longer launch, saying it can't find libpng16.so.16.

I re-deployed and got the same error.
I tried re-ordering my buildpacks (https://github.com/jontewks/puppeteer-heroku-buildpack before heroku/nodejs) but that didn't help either.

Any ideas?

```
Symfony\Component\Process\Exception\ProcessFailedException: The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/app/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/tmp\/0711007001528143524\/index.html","action":"screenshot","options":{"type":"png","path":"\/app\/storage\/app\/downloads_tmp\/81_page1.png","args":["--no-sandbox","--disable-setuid-sandbox"],"viewport":{"width":1200,"height":1000,"deviceScaleFactor":3},"displayHeaderFooter":false,"fullPage":true,"omitBackground":true}}'" failed.

Exit Code: 1(General error)

Working directory: /app

Output:
================


Error Output:
================
Error: Failed to launch chrome!
/app/node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
```

**Comment by solarsilk** [comment]
I just took a guess (I'm no expert with this) and forked the repo (https://github.com/solarsilk/puppeteer-heroku-buildpack) and added libpng16.so.16. Deployed on Heroku and got this:

![screen shot 2018-06-05 at 8 57 32 am](https://user-images.githubusercontent.com/1180968/40977364-bff1ab84-689e-11e8-8aa1-1dee87bd9016.png)

Any ideas for me? Thank you.

**Comment by solarsilk** [comment]
is this applicable here? https://askubuntu.com/questions/701246/libpng16-so-16-not-found-how-to-get-it

**Comment by jontewks** [comment]
@solarsilk hey sorry, full time job and kids taking up all my time!

You said it was working and then stopped, so we should see if we can figure out what changed. 

What does your package.json look like? Have you pinned packages to exact patch versions or are they within a range that some update to puppeteer could have caused an issue?

Also libpng16 isn't listed as a chromium dependency, so I'm wondering if it is tied to something else.

When you reordered your buildpacks, did you do a full deploy afterwards by pushing code? Simply reordering them or restarting dynos isn't enough to force the change.

Also if you can share any code that you are running that will be helpful, mainly to see if the sandbox flags are being included.

**Comment by solarsilk** [comment]
thanks so much @jontewks. 

yes, i've been pushing commits each time i try these different approaches i mentioned above.

In an effort to fix the issue, i changed puppeteer from `"puppeteer": "^1.3.0"` to `"puppeteer": "^1.4.0"`, so here's my latest package.json:
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "bootstrap-sass": "^3.3.7",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^1.0",
        "lodash": "^4.17.4"
    },
    "dependencies": {
        "axios": "^0.18.0",
        "puppeteer": "^1.4.0"
    }
}
```
this is a laravel app. i'm running a web dyno and a worker dyno. i'm queueing the jobs in laravel and executing them on the worker dyno.

i'm using the https://github.com/spatie/browsershot package to do screenshots. The package has a way to set a custom chrome binary path: https://github.com/spatie/browsershot/blob/master/README.md#custom-chromechromium-executable-path do you think this may help?

Here's some PHP code i'm using:

```
            Browsershot::html($this->html1)
                ->setOption('args', ['--no-sandbox', '--disable-setuid-sandbox'])
                ->fullPage()
                ->windowSize(1200, 1000)
                ->hideBackground()
                ->deviceScaleFactor(3)
                ->border(80, '00000000', Manipulations::BORDER_EXPAND)
                ->save($p1img);
```
as you can see in my original post, the sandbox flags look like they are being set, or at least passed to puppeteer from the browsershot code.

thank you for your help! I'm going to keep trying to think of other options.

**Comment by solarsilk** [comment]
wow, i just downloaded the heroku repo plugin, and purged the slug build cache:
```
$ heroku plugins:install https://github.com/heroku/heroku-repo.git
$ heroku repo:purge_cache -a appname
```
chrome is launching and everything is working again!

a helpful link: http://engineering.generalassemb.ly/post/143896522629/the-heroku-build-cache-and-exceeding-compiled-slug

i just read how Heroku's slug complier caches some dependencies to make the builds faster. there may have been an update to a package i'm using that had a change or something, but Heroku was caching parts of the slug and using the old files. so, running the above commands refreshed the slug and built it from scratch. i could see all the builds happening in the deploy progress output.

good to know for the future.  and btw, it also brought my slug size down from 313MB to 277MB.

thanks for being willing to help, @jontewks! really appreciate it.

**Comment by jontewks** [comment]
Thanks for the response with what worked to fix it. Glad to know to add that to the list of potential fixes for random things that pop up!

**Comment by disaacson** [comment]
Worked! Thanks.

**Comment by ziadrida** [comment]
Should PUPPETEER_SKIP_CHROMIUM_DOWNLOAD be set to false? When I do that the slug size goes over 500 MB! If it set it to true then I get the error:

2019-04-25T14:33:41.880351+00:00 app[web.1]: launchOptions: { args: [ '--no-sandbox', '--disable-setuid-sandbox' ] }
2019-04-25T14:33:42.426366+00:00 app[web.1]: Error lunching puppeteer: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
2019-04-25T14:33:42.426382+00:00 app[web.1]:     at Launcher.launch (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/puppeteer/lib/Launcher.js:119:15)
    at <anonymous>
 => awaited here:
    at Function.Promise.await (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at Promise.asyncApply (app/api/graphql/quotation/resolvers/mutation/x-ray-chrome.js:62:30)
    at app/.meteor/heroku_build/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

**Comment by jontewks** [comment]
@ziadrida that defaults to false, you'd only set it to true if you already had chrome installed and didn't want puppeteer to use the packaged version. It sounds like you might have a bunch of other things getting installed along with puppeteer and are going over your slug max on heroku. I'd follow up with them about your slug size, or see what you can remove to lower it. Chrome is quite a large download, but you need it in some form to use puppeteer. 

If you have any issues with this buildpack specifically, feel free to open up a new issue.
