### ISSUE TITLE
--disable-setuid-sandbox flag still needed?

### ISSUE THREAD

**Issue by bradoyler** [jontewks/puppeteer-heroku-buildpack#15]
FYI. I'm using Node 8.11 + puppeteer@1.7 + this buildpack w/o the `--disable-setuid-sandbox` and it seems to run fine on Heroku.

**Comment by jontewks** [comment]
Ah somehow I removed the watch on this repo and missed this. Thanks for the info. I'll confirm as well and update the readme.
