### ISSUE TITLE
Heroku Dashboard shows "Google Chrome"

### ISSUE THREAD

**Issue by ledlamp** [jontewks/puppeteer-heroku-buildpack#16]
On Heroku Dashboard the buildpack is shown as "Google Chrome"; is it because of this?
https://github.com/jontewks/puppeteer-heroku-buildpack/blob/14e3d72904c446eb7e75dac84bed1cac9159f19e/bin/detect#L4
So shouldn't it be `echo "Puppeteer"`?

**Comment by jontewks** [comment]
Accidentally removed my watch from this repo and missed this.

Also yes, thanks for catching that lol. I started with Heroku's Chrome buildpack as a base and missed this file completely. Updated.

🙇
