### ISSUE TITLE
Crashing my app

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [jontewks/puppeteer-heroku-buildpack#17]
If I add this buildpack to my application my app will crash when I try to deploy it to Heroku. If I then remove the buildpack, without altering any other file just simply removing the buildpack, the app will run without errors. 

Is this a bug with this buildpack or why might my app crash whenever I add this buildpack?

**Comment by jontewks** [comment]
Hey Sebastian, sorry I removed the watch from this repo on accident and missed this. Were you able to resolve the problem?
