### ISSUE TITLE
Heroku build fails without manually adding dependencies

### ISSUE THREAD

**Issue by benfb** [jontewks/puppeteer-heroku-buildpack#22]
After upgrading to the latest versions of the build pack and puppeteer (1.8.0), I had to manually add in `libcairo-gobject2`, `libxinerama1`, and `libgtk2.0-0` as dependencies. I see that those were removed in the most recent commit to this project. Am I missing something or should they be added back in?

**Comment by jontewks** [comment]
Thanks @benfb. The most recent commit matches the list found here: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Would you also mind trying purging your cache on heroku with these instructions:
https://github.com/jontewks/puppeteer-heroku-buildpack/issues/14

Its pretty strange that it works well for some people and not others. If the above doesn't fix it for you perhaps I can just add all the dependencies ever needed and leave them there even for people who aren't running into these issues as a safety measure, they aren't that big so probably won't cause issues.

**Comment by daneren2005** [comment]
I was able to reproduce that even after clearing the cache I still get the same error: `/app/node_modules/puppeteer/.local-chromium/linux-588429/chrome-linux/chrome: error while loading shared libraries: libcairo-gobject.so.2: cannot open shared object file: No such file or directory`.  The reason some people might be getting it and not others probably has to do with trying to use different versions of Puppeteer.  Older versions probably link against versions of Chromium that don't require it.

**Comment by jontewks** [comment]
Thanks for all the info everyone. Glad to hear when things aren't working since I was getting false positives in my testing. The missing deps should be back and I added a new release for them as well if you want to pin your buildpack down to a certain point in time.

**Comment by daneren2005** [comment]
Tested it out and it worked.  Thank you!

**Comment by jontewks** [comment]
@daneren2005 thanks for confirming as well. I'll just start only adding dependencies as they show up and never remove them to be safe!
