### ISSUE TITLE
'node': No such file or directory

### ISSUE THREAD

**Issue by RaphArbuz** [jontewks/puppeteer-heroku-buildpack#40]
Thank you for making this buildpack!

When trying to run some command line scripts with "heroku run", I get the following error:
"/usr/bin/env: 'node': No such file or directory"
My scripts all starts with the line:
"#!/usr/bin/env node"
and work fine without the buildpack.

What shall I do? 

Thank you very much for your help!

**Comment by SelaliAdobor** [comment]
I ran into the same issue a few minutes ago and came here looking for a solution 😁 

Looks like you just need another buildpack with `node`

> heroku buildpacks:add --index 1 heroku/nodejs

**Comment by RaphArbuz** [comment]
Thank you so much @SelaliAdobor . That did the trick!

**Comment by jontewks** [comment]
Yeah thanks for the reply @SelaliAdobor, I was on vacation and would have missed this for a while. 🎉
