### ISSUE TITLE
Problem with chrome

### ISSUE THREAD

**Issue by CarlosEduR** [jontewks/puppeteer-heroku-buildpack#44]
I had a problem to launch chrome when executing a node script which uses puppeteer lib. Then found puppeteer-heroku-buildpack, added  '--no-sandbox' and '--disable-setuid-sandbox' args in puppeteer.launch and ran heroku buildpacks:set jontewks/puppeteer. 

After script runs page.goto() it should wait for a certain selector, but it always timeout 30000ms. I tried to show html page in console, but it just says 'Under maintenance...'.

**Comment by jontewks** [comment]
Hey @CarlosEduR. This buildpack is for getting puppeteer running on Heroku. It sounds like it helped with that issue, but now you're running into issues using puppeteer to do what you want at a certain site. Thats out of the scope of this buildpack as its only use is to get puppeteer running. 

I'd suggest opening an issue on the puppeteer repo itself as that would be a much better place to start the discussion around how to use puppeteer once its running. https://github.com/GoogleChrome/puppeteer

**Comment by altherlex** [comment]
> I had a problem to launch chrome when executing a node script which uses puppeteer lib. Then found puppeteer-heroku-buildpack, added '--no-sandbox' and '--disable-setuid-sandbox' args in puppeteer.launch and ran heroku buildpacks:set jontewks/puppeteer.
> 
> After script runs page.goto() it should wait for a certain selector, but it always timeout 30000ms. I tried to show html page in console, but it just says 'Under maintenance...'.

got the same here
