### ISSUE TITLE
using firefox-puppeteer

### ISSUE THREAD

**Issue by ejames17** [jontewks/puppeteer-heroku-buildpack#45]
HI @jontewks  im wondering how could we use this buildpack with firefox-puppeteer https://github.com/GoogleChrome/puppeteer/tree/master/experimental/puppeteer-firefox
I  am thinking I would have to create a new buildpack?

**Comment by jontewks** [comment]
Yeah it very likely would have different package requirements and would probably be a good idea to opt in to the correct buildpack for whichever you will want to use so we don't need to install a bunch of dependencies when they usually won't be used. If you're inclined you can probably fork this and change the packages that get installed to allow FF to run on heroku.
