### ISSUE TITLE
High Memory?

### ISSUE THREAD

**Issue by mikecann** [jontewks/puppeteer-heroku-buildpack#49]
Thanks for this buildpack, really appreciate it. 

Im running this after the standard nodejs buildpack but im getting really high memory usage. 

![image](https://user-images.githubusercontent.com/215033/59959075-042c2600-94e3-11e9-8e76-1a86b415b785.png)

A slug size of 443mb means that my app is pretty much instantly running out of memory...

Is there anything I can do to help with this?

**Comment by jvandenaardweg** [comment]
The slug size is the disk size of your app, not memory size

https://devcenter.heroku.com/articles/slug-compiler#slug-size

**Comment by mikecann** [comment]
@jvandenaardweg yep.... hmm... okay thanks.
