### ISSUE TITLE
Fails to launch puppeteer due to missing package

### ISSUE THREAD

**Issue by robertistok** [jontewks/puppeteer-heroku-buildpack#5]
Hey!

I've added the buildpack to my Heroku application and deployed it. However, when the app tries to launch puppeteer, it gives the following error:

`Error: Failed to launch chrome!
/app/node_modules/puppeteer/.local-chromium/linux-515411/chrome-linux/chrome: error while loading shared libraries: libcairo-gobject.so.2: cannot open shared object file: No such file or directory`

Do you have any idea what the problem could be?

Thanks.

EDIT:
#6 Submitted a pull request to fix the issue

**Comment by korroktheslavemaster** [comment]
Same issue here

**Comment by korroktheslavemaster** [comment]
Now it fails to launch due to `libXinerama.so.1`

**Comment by jontewks** [comment]
Thanks @robertistok and @korroktheslavemaster for letting me know. Can you both check that you are running Puppeteer with the following flags set? `const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']})`. 

I just double checked the dependencies on Puppeteer and chromium and the current list is correct, and its been working for me on Heroku for quite some time. We can figure it out one way or another though!

**Comment by stanislasdrg** [comment]
Exact same issue as @robertistok 
@korroktheslavemaster Is there a way to manually install dependencies in Heroku ?

**Comment by stanislasdrg** [comment]
@jontewks In my case, I have the same flags set. Are you running Heroku-16 stack ?

**Comment by jontewks** [comment]
@stanislasdrg yeah I'm also on Heroku 16. Looking at the list of [installed dependencies](https://devcenter.heroku.com/articles/stack-packages) for Heroku 16 it looks like the package in question is available, but they mark it as only available during build time and not at run time. 

If you find a chance, can you try redeploying your app and forcing it through the build phase again? I'm not able to repro this issue on any of my deployed apps at the moment. If that doesn't fix it I'll accept that PR to add it, I don't think there is any downside to extra deps unless someone is hitting the max slug size or something

**Comment by jontewks** [comment]
@robertistok @korroktheslavemaster @stanislasdrg looking at what I originally had for this buildpack I'm seeing those deps manually installed even though they are available on heroku. I guess that makes a difference on Heroku but not when running debian manually so I'm going to accept #6 and also add the additional ones that were there before

**Comment by jontewks** [comment]
Created the new release with all deps here: https://github.com/jontewks/puppeteer-heroku-buildpack/releases/tag/v1.1.1

**Comment by jontewks** [comment]
Thanks again for the quick issue creation!

**Comment by robertistok** [comment]
Thanks for creating this package! :)

**Comment by voduycan** [comment]
Hi! please help me!, I am a newbie in Heroku-18

my buildpacks:
https://github.com/mcollina/heroku-buildpack-graphicsmagick
https://github.com/royalgarter/heroku-buildpack-phantomjs-2.0
https://github.com/heroku/heroku-buildpack-apt
heroku/nodejs
https://github.com/heroku/heroku-buildpack-google-chrome

heroku: 18

puppeteer: 1.8.0

project: Node JS

All worked fine for me but I need chrome headless = false

I changed "https://github.com/heroku/heroku-buildpack-google-chrome" to "https://github.com/royalgarter/heroku-buildpack-xvfb-google-chrome" then error: "libcairo-gobject.so.2: cannot open shared object file: No such file or directory"

I need another buidpack or a another way to launch Chrome with headless = false.

Thank for help!

**Comment by jontewks** [comment]
Hey @voduycan. Heroku doesn't have a GUI, and so running puppeteer in `headless: false` mode won't work. You can still do all the same things when running in `headless` mode on heroku, but you won't be able to inspect it visually. Screenshots are a good way to see what puppeteer is doing at any point in time though.

**Comment by voduycan** [comment]
@jontewks Hi, I need to run puppeteer with headless: true (GUI) to do some works. so what any way I can do it?

**Comment by jontewks** [comment]
Run it locally instead of on heroku. Then once you have your scripts set up you can run it headless on heroku if you need. This buildpack is for getting puppeteer running on heroku, so if you have further questions about how to use puppeteer or about running it with a GUI locally, you might be better off asking on the puppetter repo or in their forums.

**Comment by voduycan** [comment]
I have a captcha step, so I need GUI. my project is booking ticket automatic on other website. and this web has captcha step in booking

**Comment by jontewks** [comment]
Captchas are designed to stop things like puppeteer from running without a human, so you probably don't want to use heroku for this. Again this buildpack is just for getting puppeteer running on heroku, so anything beyond that I can't guarantee any help. If you have any issue with this buildpack specifically feel free to open a new issue but like I mentioned, you probably want to look elsewhere for next steps.
