### ISSUE TITLE
Latest version of puppeteer increases slug size dramatically

### ISSUE THREAD

**Issue by econner** [jontewks/puppeteer-heroku-buildpack#50]
Just wanted to post this here for the SEO as it took me quite awhile to figure out and others on Heroku are likely to hit it.

> Compiled slug size: 500.6M is too large (max is 500M)

For me latest version of puppeteer (1.18.0) on linux downloads all these files,
![image](https://user-images.githubusercontent.com/527947/60069394-6e9dbb80-96c7-11e9-8538-b3a3acdc10fc.png)

This version of Chromium completely blew away my Heroku slug size. Here is the puppeteer issue,
https://github.com/GoogleChrome/puppeteer/issues/4610
Reverting to 1.17.0 fixes it. Update occurred just a few days ago so timeline fits and installing 1.17.0 dropped my slug size back down by about 200 mb.

**Comment by jota** [comment]
Thanks @econner for posting this, that just saved me a lot of time!

**Comment by pieroliviermarquis** [comment]
So what's the solution? I have the same issue. My slug size is too big.

**Comment by markymc** [comment]
Looks like this was a bug and was fixed in a subsequent release https://github.com/puppeteer/puppeteer/issues/4610#issuecomment-506028378
