### ISSUE TITLE
Packages reinstalled on every build

### ISSUE THREAD

**Issue by feimosi** [jontewks/puppeteer-heroku-buildpack#51]
I've noticed the buildpack forces all required packages to be reinstalled even if they are at their latest versions. What's the rationale behind this? It makes deployment significantly longer and I'm looking for a way to optimize it. I'd appreciate any help and hints.

**Comment by jontewks** [comment]
Hey @feimosi, which packages are you talking about in particular? I bet there are some we could remove as I haven't updated this since cedar-14 was removed I think.

I saw in your branch you were making updates to the fonts that are installed too, if you do those updates please feel free to open a PR over here so everyone can benefit if you'd like!

**Comment by feimosi** [comment]
Thanks for the quick response. Let me clarify, I meant that all packages are reinstalled on every build, instead of just updating new packages. That's `--reinstall` option here: 
https://github.com/jontewks/puppeteer-heroku-buildpack/blob/master/bin/compile#L67

Here's a fragment from my build logs (see `1 reinstalled`). 

```
remote: -----> Fetching .debs for libc6                    
remote:        Reading package lists...                    
remote:        Building dependency tree...                 
remote:        0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 50 not upgraded.                          
remote:        Need to get 0 B/2,577 kB of archives.       
remote:        After this operation, 0 B of additional disk space will be used.                                        
remote:        Download complete and in download only mode 
remote: -----> Fetching .debs for libcairo2                
remote:        Reading package lists...                    
remote:        Building dependency tree...                 
remote:        0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 50 not upgraded.                          
remote:        Need to get 0 B/555 kB of archives.
remote:        After this operation, 0 B of additional disk space will be used.                                        
remote:        Download complete and in download only mode 
```

I was wondering if we could skip reinstalling packages.


Regarding my own changes to the project, I've been trying to make puppeteer render emoji icons properly. Unfortunately even with fonts installed, it's not working at all, still looking for a solution.

There's one more issue I'm struggling with but probably not caused by this buildpack. We're running puppeteer to render images dynamically under given URL and sometimes it simply crashes with:
`Error: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is` or
`Error: Failed to launch chrome!`
Maybe you have encountered something like that?

**Comment by jontewks** [comment]
Hey @feimosi sorry was out on vacation. 

I haven't seen anything like that during any of our use cases.

I have the --reinstall flag there only because I based this buildpack off of the heroku chrome buildpack, and they had it there at the time, and still do now. I'm not positive why they do or if its even required to function correctly. Having this buildpack as close to the official chrome one with updates specifically for puppeteer was my main goal. 

Have you tried it without the reinstall flag?

**Comment by jontewks** [comment]
Gonna close this as I haven't heard back. Happy to take a look at a PR with any changes you made that might have helped with the build times, but I'm still tempted to leave it as close to Heroku's buildpack as possible. If it does make a big difference I can see if someone from Heroku can comment on that part of their buildpack for us.

**Comment by feimosi** [comment]
Hey, sorry for not getting back to you earlier, I've been really busy.

I haven't tried without `--reinstall` flag, I wanted to confirm that first here. Haven't you noticed a much longer deployment time with this buildpack yourself? In our case, it's almost x2 (from 7-8 to 12-14 minutes). 
I'll look into it when I get more time.

I'm still surprised no one has reported that so far.

**Comment by mib32** [comment]
I checked in with the heroku support, they said:

```
[...] for the chrome buildpack, it was decided that its best to ensure you are testing against the latest version of chrome. Maybe there is something that can be done if you pin Chrome to a specific version and not download if you already have the current this version cached.
```

**Comment by mib32** [comment]
I checked in with the Heroku support, they said:

```
[...] for the chrome buildpack, it was decided that its best to ensure you are testing against the latest version of chrome. Maybe there is something that can be done if you pin Chrome to a specific version and not download if you already have the current this version cached.
```

**Comment by mib32** [comment]
Tried without '--reinstall' - no help.

**Comment by rockwood** [comment]
I'm seeing this as well. Each push to heroku is reinstalling every packages. I'm on heroku-18. I wonder if the cache directory isn't working as intended.
