### ISSUE TITLE
disable buildpack after initial install

### ISSUE THREAD

**Issue by nax3t** [jontewks/puppeteer-heroku-buildpack#58]
Is there a way to stop the buildpack from running every time I push new changes to production (on Heroku)?

Thanks in advance,
Ian

**Comment by jontewks** [comment]
Hey @nax3t, there is some discussion about it found here: https://github.com/jontewks/puppeteer-heroku-buildpack/issues/51. As far as not getting the buildpacks to run when pushing code, I didn't see anything like that on heroku's site, and it seemed like it is set up to cause them to run each time. There may be some way of caching the installed packages, but a few things we tried didn't work and also heroku doesn't have that in their official chromium buildpack, and so it didn't make its way into this one.

Happy to accept a PR if you are inclined to find the way to cache on heroku correctly!
