### ISSUE TITLE
Geolocation API doesn't seem to be working

### ISSUE THREAD

**Issue by michal-boruczkowski** [jontewks/puppeteer-heroku-buildpack#60]
I'm using flags as recommended:
```
const browser = await puppeteer.launch({
        headless: true,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox']
    })
```

Adding `geolocation` permissions:
```
const context = browser.defaultBrowserContext();
await context.overridePermissions(url, ['geolocation']);
```

Looks like it's granted as expected:
```
const granted = await page.evaluate(async () => {
        return (await navigator.permissions.query({ name: 'geolocation' })).state;
    });
console.log('Granted:', granted);
```

And finally setting location:
```
await page.setGeolocation({latitude, longitude});
```

But I can't get any response when trying to use browser geolocation API:
```
    page.on('console', msg => {
        for (let i = 0; i < msg.args().length; ++i)
            console.log(`${i}: ${msg.args()[i]}`);
    });


    await page.evaluate(() => {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition((position) => {
                console.log(position.coords.latitude)
            })
        }
    });
```

Is this an buildpack issue? Local version works just fine.

**Comment by jontewks** [comment]
Hey there.

So the buildpack only gets chromium running on heroku, but doesn't change anything about how chromium works once its running. I took a peek and it looked like chromium won't allow any interaction with the geolocation API over http and requires a secure connection. If you don't have an SSL cert for your heroku app this might be why.

https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only
