### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by therepo90** [jontewks/puppeteer-heroku-buildpack#65]
Great work man. Thanks.
Is there any way not to rerun whole process when deploying app ? it takes like 5 minutes in my case

**Comment by jontewks** [comment]
Hey @therepo90, there was some discussion about that in #58 and #51. A few things that were tried were no luck. I'll take a look at Heroku's official chrome buildpack that I based this off of originally and see if they've made that change, but my main goal was to have this be as reliable as possible, so I wanted to stick close to how Heroku does their official buildpacks as well. 

Same as the other issues though, if you are able to find a way to make it happen for yourself, I'm more than happy to accept that PR!

**Comment by jontewks** [comment]
Yeah still seems to be that way in the official buildpack for chrome. Please do let me know if you find a good way around that though, and submit that fix to their buildpack as well!
