### ISSUE TITLE
Error: Cannot find module './common'

### ISSUE THREAD

**Issue by emptypixels** [jontewks/puppeteer-heroku-buildpack#67]
I'm getting the following error when trying to run puppeteer on Heroku using this buildpack.

internal/modules/cjs/loader.js:969
  throw err;
    ^
	
Error: Cannot find module './common'Require stack:
- /app/node_modules/debug/src/node.js
- /app/node_modules/debug/src/index.js
- /app/node_modules/puppeteer/lib/helper.js
- /app/node_modules/puppeteer/lib/Browser.js
- /app/node_modules/puppeteer/lib/api.js
- /app/node_modules/puppeteer/lib/index.js
- /app/node_modules/puppeteer/index.js
...

**Comment by jontewks** [comment]
Whoops sorry for the slow response.

Haven't seen this issue before and from the stack trace there it appears to be something up with the puppeteer installation. Have you tried deleting the build cache on heroku and starting fresh? That would be my first guess. https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

**Comment by emptypixels** [comment]
I've tried that, and still the same error.

**Comment by jontewks** [comment]
Other than that all I can guess at is to try the newest version of puppeteer, or if thats what you have, one version prior. If thats no good then next step I'd think would be to open an issue on the puppeteer repo as I don't believe this buildpack could cause your npm install to work incorrectly. Perhaps also give a shot to running puppeteer's example code which is very simple, and then seeing if that works which could tell you if its your specific code or something deeper. Just throwing ideas out which you may have already tried, but either way good luck getting to the root!
