### ISSUE TITLE
Can't get Heroku to load this buildpack

### ISSUE THREAD

**Issue by jesshmusic** [jontewks/puppeteer-heroku-buildpack#7]
I am trying to deploy a React app using the create-react-app-buildpack that needs to load puppeteer dependencies for react-snap.
When deploying I am getting this error, which actually seems to freeze the build process on Heroku:
```
(node:629) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
/tmp/build_2e66391b352738bb3c9a1b44c5632458/jesshmusic-living_music_database-ca09d15273a13f10f1a1a9e7ffd147503a55dc26/node_modules/react-snap/node_modules/puppeteer/.local-chromium/linux-499413/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
(node:629) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have attempted to add the `puppeteer` build pack as described in the troubleshooting link above but it doesn't do any good. 
As a matter of fact Heroku does not load the buildpack at all.
My Heroku build packs are listed as:
```
1. https://github.com/mars/create-react-app-buildpack.git
2. https://github.com/jontewks/puppeteer-heroku-buildpack.git
```

**Comment by jontewks** [comment]
@jesshmusic can you try it with the puppeteer buildpack first in the list? I remember someone mentioning that order mattered when installing dependencies. Other than that I don't think I'll be able to help out, since this issue is getting another buildpack to run correctly and not just puppeteer.

**Comment by jamez14** [comment]
For what it's worth, order does matter. I had to put the puppeteer buildpack **before** the Node buildpack and then it worked!
<img width="806" alt="screen shot 2018-01-07 at 9 43 21 pm" src="https://user-images.githubusercontent.com/2854919/34657419-ceb750f8-f3f3-11e7-9da3-bebd44734658.png">

**Comment by jontewks** [comment]
Thanks for the info. Interesting that on our production use of it we have my buildpack second:
![image](https://user-images.githubusercontent.com/3970573/34736791-f337145a-f528-11e7-9107-cf13b5e55352.png)
I'll definitely keep it in mind about potential troubleshooting solutions though if people are experiencing weird issues in the future.
