### ISSUE TITLE
Invalidate the cache on stack upgrade

### ISSUE THREAD

**Issue by edmorley** [jontewks/puppeteer-heroku-buildpack#72]
Hi!

Thank you for adding support for Heroku-20 so fast (https://github.com/jontewks/puppeteer-heroku-buildpack/commit/6b7b7b8df5a0d9a7d8fb422ff17725359420eda9).

I noticed that currently the buildpack doesn't invalidate the cache when the app's `$STACK` changes, which would presumably cause issues depending on changes to the format of APT's cache between Ubuntu versions. (And even if APT is safely migrates/ignores old files, the cache would presumably be bloated with the previous distro's .deb files, so would be good to clean it out regardless.)

A possible pattern for solving this would be:
https://github.com/heroku/heroku-buildpack-apt/blob/0357ec1e8863a803ada6c2d57f0850f2c5fa0366/bin/compile#L32-L41

Many thanks :-)

**Comment by jontewks** [comment]
Thanks a lot @edmorley. I'm going to leave this issue open and take a look at doing this soon. It shouldn't be hard, especially with the helpful code pointer you provided, I just want to dedicate enough time to thoroughly testing it to be sure I won't ruin anyone's projects for a time.

**Comment by edmorley** [comment]
In case it helps others debugging, another variation of error message that can occur due to this issue, after upgrading to Heroku-20 is:

```
error while loading shared libraries: libnettle.so.6: cannot open shared object file: No such file or directory
```

**Comment by jontewks** [comment]
Thanks again @edmorley, going to work on this today after a long vacation where I didn't do any programming at all.

**Comment by edmorley** [comment]
Hi :-) We've had a few more customers open support tickets due to slug size increases after upgrading stack when using this buildpack. I think this may be due to the lack of cache invalidation. I don't suppose you had a chance to look into this?

**Comment by jontewks** [comment]
Lol thanks @edmorley I actually did start it and promptly forgot about it. Picking it back up now.

Side note: wouldn't it be a good idea for heroku to wipe the entirety of the cache on a stack upgrade? Libraries available at buildtime and runtime are different across stacks, so wouldn't it be good to have their project fail right then when they know what the issue is rather than at a later time when the cached files finally go away? 

I have no idea how it works internally so that might be a silly question but just a thought.

**Comment by jontewks** [comment]
Alright it appears to be working. 

Here is the info when on Heroku-18
![2021-02-05_11-55-59](https://user-images.githubusercontent.com/3970573/107070725-4fbf4080-67a9-11eb-8ad8-e698030c8ba1.png)

And after clicking upgrade stack and pushing an empty commit:
![2021-02-05_11-51-49](https://user-images.githubusercontent.com/3970573/107070687-433ae800-67a9-11eb-8680-b4561a53e59a.png)

Although the size did increase a bit, that is what it was normally on Heroku-20.

And I do see the message from the buildpack in the logs
![image](https://user-images.githubusercontent.com/3970573/107070919-9319af00-67a9-11eb-8e68-b492d9225fcd.png)

**Comment by edmorley** [comment]
> Side note: wouldn't it be a good idea for heroku to wipe the entirety of the cache on a stack upgrade?

Ideally we'd be able to, but the cache is used by several buildpacks for storage of metadata that is intended to persist across stack changes. For example sticky runtime versions for when a customer hasn't specified a Ruby/Python/... version, or in the case of the Ruby buildpack the auto-generated Rails `SECRET_KEY_BASE` (which the buildpack sets so users don't have to do so manually). In in the case of `SECRET_KEY_BASE` clearing the cache would invalidate all cookies on stack upgrade etc.

The idea of having a separate metadata store was floated, but nothing came of it. (Though guess we could go with a specific namespace in the cache as a lightweight alternative.)

**Comment by edmorley** [comment]
> Alright it appears to be working.

Awesome, thank you! :-)
