### ISSUE TITLE
Add Heroku-20 to the supported stacks list error message

### ISSUE THREAD

**Issue by edmorley** [jontewks/puppeteer-heroku-buildpack#73]
Hi :-)

Support for Heroku-20 was added in:
https://github.com/jontewks/puppeteer-heroku-buildpack/commit/6b7b7b8df5a0d9a7d8fb422ff17725359420eda9

However there is one more place to update, the error message here:
https://github.com/jontewks/puppeteer-heroku-buildpack/blob/6b7b7b8df5a0d9a7d8fb422ff17725359420eda9/bin/compile#L52

I'm presuming this was not updated initially since Heroku-20 was not yet available publicly, but we just announced the beta, so anyone can try it out now:
https://devcenter.heroku.com/changelog-items/1937

**Comment by jontewks** [comment]
Ah yes thanks!

**Comment by jontewks** [comment]
https://github.com/jontewks/puppeteer-heroku-buildpack/commit/d296af14e95666e173cf83cc8b3db983a2e6a0b1

**Comment by edmorley** [comment]
Thank you :-)
