### ISSUE TITLE
Failed to launch the browser process! (Error while loading shared libraries: libpng12.so.0)

### ISSUE THREAD

**Issue by North-West-Wind** [jontewks/puppeteer-heroku-buildpack#74]
I added this buildpack to Heroku and install the `puppeteer` package to my project. When I tried to call `puppeteer.launch({ args: ['--no-sandbox'] })` or `puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] })`, this error appears and here they are:
```
2020-10-27T11:06:02.131037+00:00 app[worker.1]: Error: Failed to launch the browser process!
2020-10-27T11:06:02.131046+00:00 app[worker.1]: /app/node_modules/puppeteer/.local-chromium/linux-809590/chrome-linux/chrome: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```
I don't know what `libpng12.so.0` is, but it seems like a library or something is missing.

**Comment by jontewks** [comment]
Hey @North-West-Wind 

Have you tried the troubleshooting steps in the readme about clearing cache?
What stack on heroku is this running on?

**Comment by North-West-Wind** [comment]
I tried clearing cache and pushed an empty commit and that did not work.

It is running on heroku-18

**Comment by jontewks** [comment]
Did you happen to upgrade from a previous heroku stack to this? I'm confused as to why you are seeing this issue and nobody else is, since libpng12 isn't a listed requirement of puppeteer (https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md). My only guess is that it was available at build/run time for heorku-16 but is an upgraded version for heroku-18.

The last thing I'd try is to start a new heroku project on heroku-18 and add node and this buildpack and then push your existing code and see if the new project resolves it.

**Comment by North-West-Wind** [comment]
I just tested it with a newly created project, and it doesn't work. The exact same error occurs.

**Comment by jontewks** [comment]
Thanks for trying that. Last question now: what version of puppeteer are you using? And are you able to share the code you are trying to run? I keep a very small test project just to verify changes to the buildpack work and its still working currently, so not quite sure whats up yet.

**Comment by North-West-Wind** [comment]
I am using `puppeteer` v5.4.0 and here's my code:
```js
  const browser = await puppeteer.launch(options);
  var result = { error: true };
  try {
    const page = await browser.newPage();
    await page.goto("https://matchmaker.krunker.io/game-list?hostname=krunker.io");
    const element = await page.$("pre");
    const servers = JSON.parse(await (await element.getProperty('textContent')).jsonValue());
    servers.error = false;
    result = servers;
  } catch(err) {
    result.message = err.message;
  } finally {
    await browser.close();
  }
  return result;
```
If you head to that link, you will get a JSON response and you may wonder why I need to use `puppeteer`. The fact is, this site blocks requests from programs to avoid attackers, so I need to use `puppeteer` in order to read the JSON.

The code emits error when running `const browser = await puppeteer.launch(options);`

**Comment by jontewks** [comment]
@North-West-Wind thanks for that. Can you please also post what your `options` object is? I’d like to be able to run the exact code you are experiencing the error with to debug. Thanks!

**Comment by North-West-Wind** [comment]
Oh sorry I forgot to include that.
```js
const options = {
    args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--no-first-run',
        '--no-zygote',
        '--single-process', // <- this one doesn't works in Windows
        '--disable-gpu'
    ],
    headless: true
};
```

**Comment by jontewks** [comment]
@North-West-Wind thanks for providing all the code. I was able to run it and it ran without issue on my heroku project. Here is an image of the code and the logs from it:

![image](https://user-images.githubusercontent.com/3970573/97882552-5f7e4300-1ce9-11eb-8e71-05a07c5a8037.png)

![image](https://user-images.githubusercontent.com/3970573/97882524-55f4db00-1ce9-11eb-93c1-4f28348a2707.png)


I'm going to close the issue just so it doesn't show up like an active problem with the buildpack, but am open to continuing to talk about whats going on and see if we can fix it for you. Perhaps at this point are you able to share the entire repo of code? And perhaps screenshots of the buildpacks included in your project?

**Comment by North-West-Wind** [comment]
Hmm weird. I just tried again with puppeteer v5.5.0 and the same error still occurs. Should I consider upgrading my stack to heroku-20?

**Comment by North-West-Wind** [comment]
Dude I just did it anyway and it worked!
