### ISSUE TITLE
Error: Failed to launch chrome! on Heroku 20

### ISSUE THREAD

**Issue by officert** [jontewks/puppeteer-heroku-buildpack#77]
I'm getting this error on Heroku after updating to Heroku 20:

Error: Failed to launch chrome!
Nov 20 13:06:19 tablelist-api-dev app/web.1 /app/node_modules/puppeteer/.local-chromium/linux-588429/chrome-linux/chrome: error while loading shared libraries: libffi.so.7: cannot open shared object file: No such file or directory

I was able to get things working by downgrading all the way back to Heroku 16, though I'm not 100% why that is. I believe Heroku 18 was working before, so might be something else. Not sure if you have any ideas. I'll update with more information as I go, switching between Heroku stacks.

**Comment by officert** [comment]
Update:

I was able to get it working again on Heroku 20 after following these steps to clear my build cache:

https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

Not sure why this works though, any ideas?

**Comment by officert** [comment]
Wondering if this issue is related to https://github.com/jontewks/puppeteer-heroku-buildpack/issues/72 and the cache not getting cleared?

**Comment by edmorley** [comment]
@officert Yeah I'm pretty sure this error was caused by the cache not being invalidated on stack upgrade (ie: #72).

**Comment by jontewks** [comment]
Hey sorry about that. Yes I'll be working on adding that here shortly. Glad you got it worked out though.
