### ISSUE TITLE
Firefox on Heroku cannot lauch multiple browsers in parallel

### ISSUE THREAD

**Issue by uri3000** [jontewks/puppeteer-heroku-buildpack#78]
When using firefox on Heroku, it is not possible to launch more than 1 browser in parallel.
Using the new firefox buildpack for puppeteer:
https://github.com/jontewks/heroku-buildpack-puppeteer-firefox

**Comment by jontewks** [comment]
@uri3000 can you please open the issue on that repo rather than here, and also please include the error you are seeing and any relevant code that might help when looking into it? Thanks.
