### ISSUE TITLE
Error: Failed to launch the browser process!  error while loading shared libraries: libnss3.so

### ISSUE THREAD

**Issue by jgu7man** [jontewks/puppeteer-heroku-buildpack#79]
I having an issue trying to launch puppeteer in heroku and I trying some solutions posted  in others issues but I don't see mine:

```
(node:21) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
2021-02-06T14:13:39.248311+00:00 app[web.1]: /app/node_modules/whatsapp-web.js/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

My stack actually is 

- Node 14
- Heroku 20
- Puppeteer 5.4

I'm running the puppteer with the suggest config 

```
{
    args: [ '--no-sandbox', '--disable-setuid-sandbox' ],
    headless: false
}
```

but the strangest thing is when I deploy my app I have some errors  like if the **puppeteer heroku buildpack** can't be installed 

These logs are displayed after the node dependencies are installed:
```
remote: -----> Build succeeded!
remote: -----> Puppeteer app detected
remote: -----> Reusing cache
remote: -----> Updating apt caches
remote:        Reading package lists...
remote: E: List directory /tmp/codon/tmp/cache/apt/state/lists/partial is missing. - Acquire (2: No such file or directory)
remote: -----> Fetching .debs for gconf-service
remote:        Reading package lists...
remote:        Building dependency tree...
remote: E: Unable to locate package gconf-service
remote: -----> Fetching .debs for libasound2
remote:        Reading package lists...
remote:        Building dependency tree...
remote: E: Unable to locate package libasound2
remote: -----> Fetching .debs for libatk1.0-0
remote:        Reading package lists...
remote:        Building dependency tree...
remote: E: Unable to locate package libatk1.0-0
remote: E: Couldn't find any package by glob 'libatk1.0-0'
remote: E: Couldn't find any package by regex 'libatk1.0-0'
remote: -----> Fetching .debs for libatk-bridge2.0-0
remote:        Reading package lists...
remote:        Building dependency tree...
remote: E: Unable to locate package libatk-bridge2.0-0
remote: E: Couldn't find any package by glob 'libatk-bridge2.0-0'
remote: E: Couldn't find any package by regex 'libatk-bridge2.0-0'
remote: -----> Fetching .debs for libc6
remote:        Reading package lists...
remote:        Building dependency tree...
remote: E: Archives directory /tmp/codon/tmp/cache/apt/cache/archives/partial is missing. - Acquire (2: No such file or directory)   
    Reinstallation of libc6 is not possible, it cannot be downloaded.
```

AND THE ERROR LIST CONTINUES LONGER... 

**I would appreciate your help or guidance**

**Comment by schuyberg** [comment]
I'm having the same problem installing the buildpack dependencies on the Heroku free tier.

**Comment by petdomaa100** [comment]
I'm also having the same problem

**Comment by jontewks** [comment]
@jgu7man thanks for bringing this up. We just made a change to how the buildpack flushes old caches out and causes this issue in rare circumstances. Can you try deploying again? The code has been updated and testing it now looks good so you, @schuyberg, and @petdomaa100 should be all set.

The next error you might run into is an issue trying to run Heroku as `headless: false`. Heroku doesn't have a GUI so when you run `headless: false` Puppeteer will try to open a browser window to show you the output which will cause a failure on Heroku. Just remove that line since the default is `headless: true`

**Comment by petdomaa100** [comment]
Thank you so much, it worked. :)

**Comment by jgu7man** [comment]
> @jgu7man thanks for bringing this up. We just made a change to how the buildpack flushes old caches out and causes this issue in rare circumstances. Can you try deploying again? The code has been updated and testing it now looks good so you, @schuyberg, and @petdomaa100 should be all set.
> 
> The next error you might run into is an issue trying to run Heroku as `headless: false`. Heroku doesn't have a GUI so when you run `headless: false` Puppeteer will try to open a browser window to show you the output which will cause a failure on Heroku. Just remove that line since the default is `headless: true`

**So much thanks! I just try it again and it works!**
