### ISSUE TITLE
Getting Error: UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `#user` failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by mahandev** [jontewks/puppeteer-heroku-buildpack#80]
![Untitled](https://user-images.githubusercontent.com/62585335/107636715-097b4d00-6c93-11eb-80a4-d905aff6b553.png)
`

**Comment by jontewks** [comment]
Hey @mahandev.

It appears as if Puppeteer waited the 30 seconds and didn't find the selector you were looking for, and exited. That sounds like Puppeteer started up successfully on Heroku, which is all this buildpack is designed to help with.

The error seems to be that something you were looking for wasn't there, so in the past when that isn't expected I'll have Puppeteer take a screenshot and upload it someplace so I can see what Puppeteer was "seeing" at the time of the failure to help debugging. 

Good luck!
