### ISSUE TITLE
Is possible to keep cached the buildpack requirements in nodejs ?

### ISSUE THREAD

**Issue by sostenesapollo** [jontewks/puppeteer-heroku-buildpack#82]
I say like, to prevent to reinstall in every build

**Comment by jontewks** [comment]
Hello @sostenesapollo.

It's been talked about in the past, but I'm basing this buildpack off of the official chrome buildpack from heroku, and they don't have any package caching and so to keep it as reliable as possible, I don't want to diverge from the official buildpack too far. It was previously talked about in this issue which links to a few others too. https://github.com/jontewks/puppeteer-heroku-buildpack/issues/65

Happy to take a look at a PR if you wanted to do it though!
