### ISSUE TITLE
Support different character sets

### ISSUE THREAD

**Issue by stefanvermaas** [jontewks/puppeteer-heroku-buildpack#84]
Hi @jontewks,

I'm not sure whether this is the right place to ask. So, please tell me when I need to open up an issue somewhere else. 

We're using the `puppeteer-heroku-buildpack` to create PDF's (using [Grover](https://github.com/Studiosity/grover)). This works great for the Latin alphabet, but things seem to go wrong for the [Hungarian alphabet](https://en.wikipedia.org/wiki/Hungarian_alphabet) (which is an extension of the Latin alphabet). 

Do you have an idea what I can, so we can support the Hungarian alphabet too? 

Cheers and thanks for this awesome project!

**Comment by jontewks** [comment]
Hey @stefanvermaas. I know of this fork that added support for other characters, perhaps this would be the easiest way for you? https://github.com/CoffeeAndCode/puppeteer-heroku-buildpack

If that doesn't work, perhaps you could post your code so I could replicate it easily and see how we might be able to resolve it?

**Comment by stefanvermaas** [comment]
Yeah, I saw that one too, but I wasn't entirely sure how it worked and where it got the additional font sets from. Also with this fork, any upstream change needs to be manually applied to the fork, so I don't think this is a sustainable way in the long run.

I created a small example app to demonstrate the issue; https://github.com/stefanvermaas/latin-extended-charset-demo-app

The following is copy/pasted from the bottom of the readme, so these thoughts are also part of this issue :)!

> ## Relevant research and options
>
> - [Add foreign charset support to Docker](https://github.com/puppeteer/puppeteer/issues/1824) - My guess this will be comparable for Heroku where a buildpack could install the needed fonts, but I'm not sure.
> - [This fork of the @jontewks buildpack adds support for Chinese, Korean, and Japanese characters.](https://github.com/CoffeeAndCode/puppeteer-heroku-buildpack)
> 
> The fork has one downside in my opinion; it needs to be kept up-to-date with the original repository. It might be useful to add new buildpacks with support for specific languages.
> 
> However, I'm not sure (1) whether you can "extend buildpacks" in a way or make them dependent on another buildpack and (2) how to get the fonts that support the other languages.

Hope this helps.

**Comment by stefanvermaas** [comment]
I just noticed the comment in the mentioned issue (e.g. "Add foreign charset support to Docker"), which [points out how to install additional charsets for Docker](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker). 

I imagine this should be doable for this buildpack too. However, I'm not sure whether or not you can make things configurable in a buildpack or it can/should be extended in some way.

**Comment by stefanvermaas** [comment]
Okay, so I've further investigated the options for us as the proposed solution (allowing people to install new packages through an environment variable) is a bad idea. It turns out there are several buildpacks already out there which can help with installing extra fonts/charsets. 

However, our problem turned out to be related to a missing `meta` tag with the charset set to `UTF-8`. Adding this missing meta tag allowed Puppeteer to pick up the right charset and fixed all of our problems. I'll close this issue as there are better approaches that are not related to this repo. 

Thanks, @jontewks for taking the time to answer my questions!

**Comment by jontewks** [comment]
Thanks for providing that update on the solution @stefanvermaas!
