### ISSUE TITLE
Puppeteer Extra

### ISSUE THREAD

**Issue by 7Blasther** [jontewks/puppeteer-heroku-buildpack#87]
Hi, @jontewks! I was wondering how to run this with 'puppeteer-extra' instead of the regular puppeteer. To be more specific, I'd like to add the stealth plugin 'puppeteer-extra-plugin-stealth' which requires 'puppeteer-extra' as a "drop-in" replacement (stated on the website) [https://www.npmjs.com/package/puppeteer-extra](url). I have no idea how to manage this and some help would be greatly appreciated. Thanks!

**Comment by jontewks** [comment]
This buildpack just installs the libraries needed to run chromium in puppeteer. I'd imagine you just use puppeteer-extra instead and do everything else the same. Have you tried it yet? Just try running this exact code from the quickstart section of the readme on heroku and see if it runs. If you get actual errors you can go from there. 

https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra#quickstart
