### ISSUE TITLE
Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by Dhanani** [jontewks/puppeteer-heroku-buildpack#9]
Hi,

I'm getting ```/chrome-linux/nacl_helper: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory``` when my server attempts to launch  chrome. This is strange as this was working a few days ago and now it's not.

Thank you!

**Comment by jontewks** [comment]
Haven't seen this before, was it an issue with this buildpack? If so would you please comment on what you did to resolve it in case anyone else runs into the same issue in the future?

**Comment by Dhanani** [comment]
Hi,

There is nothing wrong with this buildpack for me. I accidentally set the headless flag to false.
