### ISSUE TITLE
Local: Puppeteer is scraping data, however on Heroku with jontewks build pack not scraping?

### ISSUE THREAD

**Issue by juliusoh** [jontewks/puppeteer-heroku-buildpack#92]
Hello

I have line of code like this

`const addCoin = async (req, res) => {
  const { username, password, coinId, seconds, bidAmount } = req.body;
  console.log(coinId);

  const coinExists = await Coin.findOne({ itemId: coinId });
  console.log(coinExists);
  if (coinExists) {
    res.status(400).send({ message: 'Coin Exists Bad Request' }); // bad request
    throw new Error('Coin already exists');
  }

  const { browser, page } = await startBrowser();
  console.log('scraping...');
  console.log(page.url());
  const request = await fetch(`}`);
  await page.goto(`}`);
  await page.screenshot({
    path: `frontend/public/assets/${coinId}.png`,
  });
  const text = await request.text();
  const $ = cheerio.load(text);
  const coinImage = $('#one img').attr('src');
  const coinTitle = $('#three div h1').text();
  const bids = $('#bidsrow td input').attr('value');
  const timeLeft = $('#endsrow #endstext').text();
  const currentBid = $('#currentbidtext').text();
  const itemId = $('#itemidrow td .bolder').text();
  const minBid = $('#minimumbidtext').text().replace('$', '');

  const coinData = new Coin({
    username,
    password,
    coinImage,
    coinTitle,
    bids,
    timeLeft,
    currentBid,
    itemId,
    seconds,
    bidAmount,
    minBid,
  });

  if (coinData) {
    const newCoin = new Coin(coinData);
    newCoin.save(function (err, result) {
      if (err) {
        res.status(400);
        console.log('error', err);
      } else {
        res.status(201).json(newCoin);
        console.log('results', result);
      }
    });`

I remove site URL's for confidential purpose. However on my local machine this is working perfectly fine, however when I deploy this to the HerokuApp with the puppeteer, its not even scraping the site nor giving me the correct scrape url website. 

This is my arguments for the puppeteer

 await puppeteer.launch({
    args: [
      '--no-sandbox',
      '--disable-gpu',
      '--disable-dev-shm-usage',
      '--disable-setuid-sandbox',
      '--no-first-run',
      '--no-zygote',
      '--single-process',
    ],
  });

**Comment by jontewks** [comment]
Hey @juliusoh. The only thing this buildpack does is allow Puppeteer to run on Heroku and doesn't have any effect on how Puppeteer runs after it starts. If you are getting different results locally vs on heroku it can be due to requests coming from a shared heroku IP that the site is blocking or some other random things like that. Best bet is to take a screenshot and save it someplace to look at later so you can see what Puppeteer is seeing at different points to determine where the failure is happening.

Good luck!
