### ISSUE TITLE
Remove support for Cedar-14 and Heroku-16

### ISSUE THREAD

**Issue by edmorley** [jontewks/puppeteer-heroku-buildpack#93]
Hi :-) 

The Cedar-14 and Heroku-16 stacks are EOL (since the upstream Ubuntu LTS releases on which they are based are EOL), and can no longer be built on the Heroku platform. See:
https://help.heroku.com/SMQ1J712/cedar-14-end-of-life-faq
https://help.heroku.com/0S5P41DC/heroku-16-end-of-life-faq

As such there is a small amount of deadcode that can be removed from this buildpack, if you wish :-)

https://github.com/jontewks/puppeteer-heroku-buildpack/blob/13797f853798a037c7eb93463963023808c9e400/bin/compile#L63-L72

**Comment by jontewks** [comment]
Thanks @edmorley just updated.
