### ISSUE TITLE
Navigation Timeout

### ISSUE THREAD

**Issue by jack567ow** [jontewks/puppeteer-heroku-buildpack#98]
I am trying To Get Amazon Link but Getting Error Navigation Time out

Link is : https://www.indiafreestuff.in/ifsredirect?ifs=NzY3MjgyNDk1Mzc=

const puppeteer = require('puppeteer');
let browser;
let page;
(async () => {
 browser = await puppeteer.launch({
  headless: true,
  args: ['--no-sandbox'],
 });
 page = await browser.newPage();
})();

function delay(n) {
 return new Promise(function (resolve) {
  setTimeout(resolve, n * 1000);
 });
}

async function followRedirect(url) {
 return new Promise(async (resolve, reject) => {
  console.log(making pupetter go to ${url});
  const isUrl = url.match(/\bhttps?:\/\/\S+/gi);
  if (isUrl) {
   try {
    const response = await page.goto(url);
    await page.waitForTimeout(10000);
    const resolvedUrl = response.request().frame().url();
    console.log(resolved to ${resolvedUrl});
    return resolvedUrl;
   } catch (err) {
    console.log(err.message);
    return null;
   }
  }
 });
}

process.on('SIGTERM', async () => {
 await page.close();
 await browser.close();
});

module.exports = followRedirect;

**Comment by jontewks** [comment]
Hey @jack567ow. This buildpack simply gets Puppeteer running on Heroku and doesn't effect how it runs after its able to start up successfully. If you think this is an issue you can always raise it on the Puppeteer repo.

The thing I'll always suggest for errors like this is to take screenshots at certain steps with Puppeteer so you can see what the browser is seeing when it fails.
