### ISSUE TITLE
heroku Error: compiled slug size: is too large with Puppeteer

### ISSUE THREAD

**Issue by adnanhassan23** [jontewks/puppeteer-heroku-buildpack#99]
My App Working on local host but when i deploy on heroku this build is required. puppeteer node_module size is around 300mb and this build size is 200 with **heroku/nodejs**.Total size is 539mb. Please suggest a good solution

**Comment by jontewks** [comment]
Hey @adnanhassan23 

Yeah chromium is pretty large and so what we've had to do previously is have a separate repo for the puppeteer code and utilize it as a microservice separate from our main app. 

I'd also check and be sure you're using the latest puppeteer as they had a version that had an issue where it increased the slug size by a lot, 1.18 I think it was.

You may also be able to go down this route depending on your needs for puppeteer: https://github.com/puppeteer/puppeteer/issues/3027#issuecomment-411211912

**Comment by wildlyinaccurate** [comment]
I ran into this issue today as well. My problem ended up being that my slug still contained files from a buildpack I had installed and later removed. These old files were removed after I [cleared the build cache](https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache) and now the slug is small enough to deploy again - so thanks @jontewks for mentioning that in the README!
